import React from 'react'

class FlightPage extends React.Component {
  render(){
    return(
      <div className="home-page">
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
        <p>FlightPage</p>
      </div>
    )
  }
}

export default FlightPage
